"""initial schema

Revision ID: 7071adf96d33
Revises:
Create Date: 2026-04-14 13:49:58.227392

"""

from collections.abc import Sequence

import sqlalchemy
from alembic import op
from sqlalchemy.dialects import postgresql

import pathfinder.persistence.models

# revision identifiers, used by Alembic.
revision: str = "7071adf96d33"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sqlalchemy.Column("id", pathfinder.persistence.models.GUID(), nullable=False),
        sqlalchemy.Column("external_id", sqlalchemy.String(length=255), nullable=True),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.PrimaryKeyConstraint("id"),
        sqlalchemy.UniqueConstraint("external_id"),
    )
    op.create_table(
        "control_sets",
        sqlalchemy.Column("id", pathfinder.persistence.models.GUID(), nullable=False),
        sqlalchemy.Column(
            "user_id", pathfinder.persistence.models.GUID(), nullable=True
        ),
        sqlalchemy.Column("name", sqlalchemy.String(length=255), nullable=False),
        sqlalchemy.Column("site_id", sqlalchemy.String(length=100), nullable=False),
        sqlalchemy.Column("record_type", sqlalchemy.String(length=100), nullable=False),
        sqlalchemy.Column("positive_ids", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("negative_ids", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("source", sqlalchemy.String(length=50), nullable=True),
        sqlalchemy.Column("tags", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("provenance_notes", sqlalchemy.Text(), nullable=True),
        sqlalchemy.Column("version", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("is_public", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_control_sets_site_id", "control_sets", ["site_id"], unique=False
    )
    op.create_index(
        "ix_control_sets_user_id", "control_sets", ["user_id"], unique=False
    )
    op.create_table(
        "experiments",
        sqlalchemy.Column("id", sqlalchemy.String(length=50), nullable=False),
        sqlalchemy.Column("site_id", sqlalchemy.String(length=100), nullable=False),
        sqlalchemy.Column(
            "user_id", pathfinder.persistence.models.GUID(), nullable=True
        ),
        sqlalchemy.Column("name", sqlalchemy.String(length=255), nullable=False),
        sqlalchemy.Column("status", sqlalchemy.String(length=20), nullable=False),
        sqlalchemy.Column("data", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("batch_id", sqlalchemy.String(length=50), nullable=True),
        sqlalchemy.Column("benchmark_id", sqlalchemy.String(length=50), nullable=True),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.Column(
            "updated_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_experiments_batch_id", "experiments", ["batch_id"], unique=False
    )
    op.create_index(
        "ix_experiments_benchmark_id", "experiments", ["benchmark_id"], unique=False
    )
    op.create_index("ix_experiments_site_id", "experiments", ["site_id"], unique=False)
    op.create_index("ix_experiments_user_id", "experiments", ["user_id"], unique=False)
    op.create_table(
        "gene_sets",
        sqlalchemy.Column("id", sqlalchemy.String(length=50), nullable=False),
        sqlalchemy.Column(
            "user_id", pathfinder.persistence.models.GUID(), nullable=True
        ),
        sqlalchemy.Column("site_id", sqlalchemy.String(length=100), nullable=False),
        sqlalchemy.Column("name", sqlalchemy.String(length=255), nullable=False),
        sqlalchemy.Column("gene_ids", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("source", sqlalchemy.String(length=20), nullable=False),
        sqlalchemy.Column("wdk_strategy_id", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("wdk_step_id", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("search_name", sqlalchemy.String(length=255), nullable=True),
        sqlalchemy.Column("record_type", sqlalchemy.String(length=100), nullable=True),
        sqlalchemy.Column("parameters", sqlalchemy.JSON(), nullable=True),
        sqlalchemy.Column("parent_set_ids", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("operation", sqlalchemy.String(length=20), nullable=True),
        sqlalchemy.Column("step_count", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_gene_sets_site_id", "gene_sets", ["site_id"], unique=False)
    op.create_index("ix_gene_sets_user_id", "gene_sets", ["user_id"], unique=False)
    op.create_index(
        "ix_gene_sets_user_site", "gene_sets", ["user_id", "site_id"], unique=False
    )
    op.create_table(
        "chats",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column(
            "user_id", pathfinder.persistence.models.GUID(), nullable=False
        ),
        sqlalchemy.Column("site_id", sqlalchemy.String(length=50), nullable=False),
        sqlalchemy.Column("name", sqlalchemy.String(length=255), nullable=False),
        sqlalchemy.Column("record_type", sqlalchemy.String(length=100), nullable=True),
        sqlalchemy.Column("wdk_strategy_id", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("is_saved", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.Column("pipeline", sqlalchemy.JSON(), nullable=True),
        sqlalchemy.Column("step_count", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("plan", sqlalchemy.JSON(), nullable=False),
        sqlalchemy.Column("estimated_size", sqlalchemy.Integer(), nullable=True),
        sqlalchemy.Column("gene_set_id", sqlalchemy.String(length=50), nullable=True),
        sqlalchemy.Column(
            "gene_set_auto_imported", sqlalchemy.Boolean(), nullable=False
        ),
        sqlalchemy.Column("experiment_id", sqlalchemy.String(length=50), nullable=True),
        sqlalchemy.Column(
            "dismissed_at", sqlalchemy.DateTime(timezone=True), nullable=True
        ),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.Column(
            "updated_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], ondelete="SET NULL"
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["gene_set_id"], ["gene_sets.id"], ondelete="SET NULL"
        ),
        sqlalchemy.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_chats_user_site", "chats", ["user_id", "site_id"], unique=False)
    op.create_index(
        "ix_chats_wdk_strategy_id",
        "chats",
        ["wdk_strategy_id"],
        unique=True,
        postgresql_where="wdk_strategy_id IS NOT NULL",
    )
    op.create_table(
        "messages",
        sqlalchemy.Column("id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("chat_id", sqlalchemy.UUID(), nullable=False),
        sqlalchemy.Column("role", sqlalchemy.String(), nullable=False),
        sqlalchemy.Column(
            "parts", postgresql.JSONB(astext_type=sqlalchemy.Text()), nullable=False
        ),
        sqlalchemy.Column(
            "metadata",
            postgresql.JSONB(astext_type=sqlalchemy.Text()),
            server_default="{}",
            nullable=False,
        ),
        sqlalchemy.Column(
            "created_at",
            sqlalchemy.DateTime(timezone=True),
            server_default=sqlalchemy.text("now()"),
            nullable=False,
        ),
        sqlalchemy.CheckConstraint(
            "role IN ('user', 'assistant', 'system')", name="ck_messages_role"
        ),
        sqlalchemy.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sqlalchemy.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "messages_chat_id_created_at_idx",
        "messages",
        ["chat_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("messages_chat_id_created_at_idx", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        "ix_chats_wdk_strategy_id",
        table_name="chats",
        postgresql_where="wdk_strategy_id IS NOT NULL",
    )
    op.drop_index("ix_chats_user_site", table_name="chats")
    op.drop_table("chats")
    op.drop_index("ix_gene_sets_user_site", table_name="gene_sets")
    op.drop_index("ix_gene_sets_user_id", table_name="gene_sets")
    op.drop_index("ix_gene_sets_site_id", table_name="gene_sets")
    op.drop_table("gene_sets")
    op.drop_index("ix_experiments_user_id", table_name="experiments")
    op.drop_index("ix_experiments_site_id", table_name="experiments")
    op.drop_index("ix_experiments_benchmark_id", table_name="experiments")
    op.drop_index("ix_experiments_batch_id", table_name="experiments")
    op.drop_table("experiments")
    op.drop_index("ix_control_sets_user_id", table_name="control_sets")
    op.drop_index("ix_control_sets_site_id", table_name="control_sets")
    op.drop_table("control_sets")
    op.drop_table("users")
    # ### end Alembic commands ###
