import type { EvidenceCard } from "@pathfinder/shared";

/** A card as `data-evidence-card` carries it: a two-kind control test on the
 * root step of a one-step plasmodb strategy that the site now counts higher. */
export const EVIDENCE_CARD: EvidenceCard = {
  checkId: "call_verify_1",
  revision: "rev-1",
  siteId: "plasmodb",
  checkedAt: "2026-09-24T09:30:00Z",
  wdkStrategyId: 300125410,
  strategyUrl:
    "https://plasmodb.org/plasmo/app/workspace/strategies/300125410/440299573",
  siteRead: "read",
  steps: [
    {
      stepId: "s1",
      wdkStepId: 440299573,
      title: "Genes by Molecular Weight",
      recordedCount: 1843,
      siteCount: 1851,
      drifted: true,
    },
  ],
  controls: [
    {
      testedLabel: "Genes by Molecular Weight",
      wdkStepId: 440299573,
      positive: {
        returned: ["PF3D7_0102600", "PF3D7_0709000"],
        notReturned: ["PF3D7_1133400"],
        controlsCount: 3,
        returnedCount: 2,
        rate: 2 / 3,
      },
      negative: {
        returned: [],
        notReturned: ["TGME49_205250", "PF3D7_1222600"],
        controlsCount: 2,
        returnedCount: 0,
        rate: 0,
      },
      enrichment: {
        population: 5,
        positives: 3,
        returned: 2,
        positivesReturned: 2,
        pValue: 0.3,
      },
    },
  ],
  citations: [
    {
      criterionId: "c1",
      criterionText: "genes of 10 to 20 kDa",
      references: ["https://doi.org/10.1038/nature12970"],
    },
  ],
  verdict: { supported: true, pendingChecks: [], refusedBecause: null },
};

/** A card a real plasmodb check left, as `data-evidence-card` carried it: the
 * signal peptide and transmembrane request, its four requirement rows, the eight
 * genes the check read, and the records it cites. */
export const REVIEWED_CARD: EvidenceCard = {
  checkId: "call_wnmmg7nv2VKh18Y33RheQEZJ",
  revision: "a1f7573c4ce2d1f3",
  siteId: "plasmodb",
  checkedAt: "2026-09-24T15:46:23.827656Z",
  wdkStrategyId: 330699223,
  strategyUrl:
    "https://plasmodb.org/plasmo/app/workspace/strategies/330699223/440597243",
  siteRead: "read",
  steps: [
    {
      stepId: "step_80bbac4f",
      wdkStepId: 440597223,
      title: "Predicted Signal Peptide",
      recordedCount: 479,
      siteCount: 479,
      drifted: false,
    },
    {
      stepId: "step_e7a86f13",
      wdkStepId: 440597233,
      title: "Transmembrane Domain Count",
      recordedCount: 840,
      siteCount: 840,
      drifted: false,
    },
    {
      stepId: "step_901d23cc",
      wdkStepId: 440597243,
      title: "Intersect",
      recordedCount: 116,
      siteCount: 116,
      drifted: false,
    },
  ],
  controls: [],
  citations: [],
  verdict: {
    supported: true,
    pendingChecks: [],
    refusedBecause: null,
  },
  review: {
    requirements: [
      {
        text: "P. falciparum 3D7 genes",
        turn: 1,
        answeredBy: ["step_80bbac4f", "step_e7a86f13"],
        how: "parameter",
        status: "met",
        note: 'Both component searches use `organism=["Plasmodium falciparum 3D7"]`.',
      },
      {
        text: "with a signal peptide",
        turn: 1,
        answeredBy: ["step_80bbac4f"],
        how: "search",
        status: "met",
        note: "`GenesWithSignalPeptide` uses `signalp_version=SignalP-6.0`.",
      },
      {
        text: "at least 2 transmembrane domains",
        turn: 1,
        answeredBy: ["step_e7a86f13"],
        how: "parameter",
        status: "met",
        note: "`GenesByTransmembraneDomains` uses `min_tm=2` and `max_tm=99`.",
      },
      {
        text: "signal peptide and at least 2 transmembrane domains",
        turn: 1,
        answeredBy: ["step_901d23cc"],
        how: "structure",
        status: "met",
        note: "The root is an `INTERSECT` of the signal-peptide and transmembrane-domain steps.",
      },
    ],
    sampledGenes: [
      {
        geneId: "PF3D7_0101000",
        product: "rifin",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `rifin`, but does not display the signal-peptide or transmembrane-domain calls.",
      },
      {
        geneId: "PF3D7_0101800",
        product: "stevor",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `stevor`, but does not display the signal-peptide or transmembrane-domain calls.",
      },
      {
        geneId: "PF3D7_0102500",
        product: "erythrocyte binding antigen-181",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `erythrocyte binding antigen-181`, but does not display the requested feature calls.",
      },
      {
        geneId: "PF3D7_0105400",
        product: "conserved Plasmodium protein, unknown function",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product, but does not display the signal-peptide or transmembrane-domain calls.",
      },
      {
        geneId: "PF3D7_0107700",
        product: "dolichyl-diphosphooligosaccharide--protein glycosyltransferase",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product, but does not display the requested feature calls.",
      },
      {
        geneId: "PF3D7_0108700",
        product: "secreted ookinete protein, putative",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `secreted ookinete protein, putative`, but does not display the requested feature calls.",
      },
      {
        geneId: "PF3D7_0113900",
        product: "CX3CL1-binding protein 1",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `CX3CL1-binding protein 1`, but does not display the signal-peptide or transmembrane-domain calls.",
      },
      {
        geneId: "PF3D7_0115400",
        product: "stevor",
        organism: "P. falciparum 3D7",
        fits: "unclear",
        why: "The record confirms the organism and product `stevor`, but does not display the signal-peptide or transmembrane-domain calls.",
      },
    ],
    sources: [
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0101000`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0101000",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `rifin`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0101800`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0101800",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `stevor`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0102500`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0102500",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `erythrocyte binding antigen-181`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0105400`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0105400",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `conserved Plasmodium protein, unknown function`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0107700`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0107700",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with a dolichyl-diphosphooligosaccharide--protein glycosyltransferase product.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0108700`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0108700",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `secreted ookinete protein, putative`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0113900`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0113900",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `CX3CL1-binding protein 1`.",
      },
      {
        kind: "record",
        label: "VEuPathDB record `PF3D7_0115400`",
        url: "https://plasmodb.org/plasmo/app/record/gene/PF3D7_0115400",
        doi: null,
        pmid: null,
        why: "Confirms the sampled gene is `P. falciparum 3D7` with product `stevor`.",
      },
    ],
  },
};
